# Generated by Django 4.1.1 on 2022-10-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=1, upload_to='post_photo/%Y/%m/%d/', verbose_name='Rasm'),
            preserve_default=False,
        ),
    ]
